apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloworld
    app.kubernetes.io/instance: helloworld
  name: helloworld
  namespace: helloworld
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
status:
  loadBalancer: {}
